#!/bin/bash

# pdfseparate OHBM2021_Schedule_key_parts.pdf Schedule_key_%d.pdf

pdfunite Schedule_key_1.pdf OHBM2021_Schedule_at_a_glance_PDT_Morning_Track.pdf OHBM2021_Schedule_at_a_glance_PDT_Afternoon_Track.pdf OHBM2021_Schedule_at_a_glance_PDT_Night_Poster_Session.pdf OHBM2021_Schedule_PDT.pdf

pdfunite Schedule_key_2.pdf OHBM2021_Schedule_at_a_glance_EDT_Morning_Track.pdf OHBM2021_Schedule_at_a_glance_EDT_Evening_Track.pdf OHBM2021_Schedule_at_a_glance_EDT_Night_Poster_Session.pdf OHBM2021_Schedule_EDT.pdf

pdfunite Schedule_key_3.pdf OHBM2021_Schedule_at_a_glance_CEST_Afternoon_Track.pdf OHBM2021_Schedule_at_a_glance_CEST_Night_Track.pdf OHBM2021_Schedule_at_a_glance_CEST_Morning_Poster_Session.pdf OHBM2021_Schedule_CEST.pdf

pdfunite Schedule_key_4.pdf OHBM2021_Schedule_at_a_glance_CST_Morning_Track.pdf OHBM2021_Schedule_at_a_glance_CST_Night_Track.pdf OHBM2021_Schedule_at_a_glance_CST_Afternoon_Poster_Session.pdf OHBM2021_Schedule_CST.pdf
